#!/bin/bash

echo ''
echo 'Building Front-End app ...'
echo '--------------------------------------------'

echo '1. install Webpack, Webpack-dev-server and Bower globally:'
echo ''
sudo npm install webpack webpack-dev-server bower -g

echo '2. install npm dependencies:'
echo ''
npm install --no-bin-links

echo '3. rebuild node-sass:'
echo ''
npm rebuild node-sass --no-bin-links

echo '4. install bower dependencies:'
echo ''
bower install

echo '5. running Webpack and build our app:'
echo ''
webpack --colors --progress --display-error-details

echo 'DONE !!!'
